[2019-08-05T01:26:13.551] [INFO] safarnama - Connected to databse
[2019-08-05T01:26:26.745] [INFO] safarnama - Connected to databse
[2019-08-05T01:26:33.544] [INFO] safarnama - Connected to databse
[2019-08-05T01:27:29.287] [INFO] safarnama - Connected to databse
[2019-08-05T01:27:58.010] [INFO] safarnama - Connected to databse
[2019-08-05T01:28:10.391] [INFO] safarnama - Connected to databse
[2019-08-05T01:28:14.573] [INFO] safarnama - Connected to databse
[2019-08-05T01:28:41.366] [INFO] safarnama - Connected to databse
[2019-08-05T01:29:26.200] [INFO] safarnama - Connected to databse
[2019-08-05T01:31:40.917] [INFO] safarnama - Connected to databse
[2019-08-05T01:32:02.037] [INFO] safarnama - Connected to databse
[2019-08-05T01:32:48.382] [INFO] safarnama - Connected to databse
[2019-08-05T01:33:01.268] [INFO] safarnama - Connected to databse
[2019-08-05T01:33:10.066] [INFO] safarnama - Connected to databse
[2019-08-05T01:33:58.847] [INFO] safarnama - Connected to databse
[2019-08-05T01:34:33.039] [INFO] safarnama - Connected to databse
[2019-08-05T01:34:37.444] [INFO] safarnama - Connected to databse
[2019-08-05T01:35:44.156] [INFO] safarnama - Connected to databse
[2019-08-05T01:36:18.281] [INFO] safarnama - Connected to databse
[2019-08-05T01:36:45.728] [INFO] safarnama - Connected to databse
[2019-08-05T01:36:49.271] [INFO] safarnama - Connected to databse
[2019-08-05T01:36:53.371] [INFO] safarnama - Connected to databse
[2019-08-05T01:37:17.221] [INFO] safarnama - Connected to databse
[2019-08-05T01:37:31.091] [INFO] safarnama - Connected to databse
[2019-08-05T01:37:39.982] [INFO] safarnama - Connected to databse
[2019-08-05T01:43:11.878] [INFO] safarnama - Connected to databse
[2019-08-05T01:43:18.022] [ERROR] safarnama - blogController - createBlog : { ValidationError: Blog validation failed: user: Path `user` is required.
    at ValidationError.inspect (D:\innovation\final\safarnama\node_modules\mongoose\lib\error\validation.js:59:24)
    at formatValue (internal/util/inspect.js:493:31)
    at inspect (internal/util/inspect.js:191:10)
    at formatWithOptions (util.js:164:18)
    at Object.format (util.js:72:10)
    at basicLayout (D:\innovation\final\safarnama\node_modules\log4js\lib\layouts.js:65:57)
    at app (D:\innovation\final\safarnama\node_modules\log4js\lib\appenders\file.js:55:18)
    at categoryAppenders.forEach (D:\innovation\final\safarnama\node_modules\log4js\lib\log4js.js:42:5)
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (D:\innovation\final\safarnama\node_modules\log4js\lib\log4js.js:41:21)
    at listeners.forEach.l (D:\innovation\final\safarnama\node_modules\log4js\lib\clustering.js:16:26)
    at Array.forEach (<anonymous>)
    at sendToListeners (D:\innovation\final\safarnama\node_modules\log4js\lib\clustering.js:16:13)
    at Object.send (D:\innovation\final\safarnama\node_modules\log4js\lib\clustering.js:78:7)
    at Logger._log (D:\innovation\final\safarnama\node_modules\log4js\lib\logger.js:86:16)
    at Logger.log (D:\innovation\final\safarnama\node_modules\log4js\lib\logger.js:69:12)
  errors:
   { user:
      { ValidatorError: Path `user` is required.
          at new ValidatorError (D:\innovation\final\safarnama\node_modules\mongoose\lib\error\validator.js:29:11)
          at validate (D:\innovation\final\safarnama\node_modules\mongoose\lib\schematype.js:978:13)
          at D:\innovation\final\safarnama\node_modules\mongoose\lib\schematype.js:1031:11
          at Array.forEach (<anonymous>)
          at ObjectId.SchemaType.doValidate (D:\innovation\final\safarnama\node_modules\mongoose\lib\schematype.js:987:14)
          at D:\innovation\final\safarnama\node_modules\mongoose\lib\document.js:2101:9
          at process._tickCallback (internal/process/next_tick.js:61:11)
        message: 'Path `user` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'user',
        value: undefined,
        reason: undefined,
        [Symbol(mongoose:validatorError)]: true } },
  _message: 'Blog validation failed',
  name: 'ValidationError' }
[2019-08-05T01:44:44.090] [INFO] safarnama - Connected to databse
[2019-08-05T01:45:06.421] [INFO] safarnama - Connected to databse
[2019-08-05T01:45:19.505] [INFO] safarnama - Connected to databse
[2019-08-05T01:46:16.981] [INFO] safarnama - Connected to databse
[2019-08-05T01:46:24.680] [INFO] safarnama - Connected to databse
[2019-08-05T01:46:50.675] [INFO] safarnama - Connected to databse
[2019-08-05T01:46:59.148] [INFO] safarnama - Connected to databse
[2019-08-05T01:47:07.701] [INFO] safarnama - Connected to databse
[2019-08-05T01:47:29.541] [INFO] safarnama - Connected to databse
[2019-08-05T01:48:19.849] [INFO] safarnama - Connected to databse
[2019-08-05T01:48:26.069] [INFO] safarnama - Connected to databse
[2019-08-05T01:48:47.842] [INFO] safarnama - Connected to databse
[2019-08-05T01:48:53.734] [INFO] safarnama - Connected to databse
[2019-08-05T01:49:07.324] [INFO] safarnama - Connected to databse
[2019-08-05T01:49:38.021] [INFO] safarnama - Connected to databse
[2019-08-05T01:49:45.134] [INFO] safarnama - Connected to databse
[2019-08-05T01:49:56.724] [ERROR] safarnama - unexpected error { Error: Not found
    at app.use (D:\innovation\final\safarnama\server\index.js:81:17)
    at Layer.handle [as handle_request] (D:\innovation\final\safarnama\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\innovation\final\safarnama\node_modules\express\lib\router\index.js:317:13)
    at D:\innovation\final\safarnama\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\innovation\final\safarnama\node_modules\express\lib\router\index.js:335:12)
    at next (D:\innovation\final\safarnama\node_modules\express\lib\router\index.js:275:10)
    at D:\innovation\final\safarnama\node_modules\express\lib\router\index.js:635:15
    at next (D:\innovation\final\safarnama\node_modules\express\lib\router\index.js:260:14)
    at Function.handle (D:\innovation\final\safarnama\node_modules\express\lib\router\index.js:174:3)
    at router (D:\innovation\final\safarnama\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\innovation\final\safarnama\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\innovation\final\safarnama\node_modules\express\lib\router\index.js:317:13)
    at D:\innovation\final\safarnama\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\innovation\final\safarnama\node_modules\express\lib\router\index.js:335:12)
    at next (D:\innovation\final\safarnama\node_modules\express\lib\router\index.js:275:10)
    at app.use (D:\innovation\final\safarnama\server\index.js:66:3) status: 404 }
